language: node_js
node_js:
    - 4.2.2
sudo: false
before_script:
  - npm install gulp
cache:
    directories:
        - node_modules
notifications:
    slack:
        rooms:
            secure: "SBxy+ntdNlzHvKEo9ySqq9a1u/VKUs3SxDahSGJRA3tF+7rzpeGIA7nBII+4zvD6bFuaZJ5pdPiV5QAC9fbhGqCjyx5MjprGfX6YmGyKXn7qT13MtRDSmy2AJ6dfy/Qu3DhLqC0+SIG79AgCEK2bJwyeh58wwcW59RgXhoTCM+HCowRNMjsJgOUcgxzM6x5hjg46PfZZ+49Jje9EI2XF5OfbP4TMQR6K/gReIRSAVGfqPkAhSTHYjr9Q0g3ctxpfTi+KjRCujc0hdNA1UvgjJJJlAgP9fiVNd38i4YpVKyvfoyLSsmyGlJp+c4P1MyBm3/+yJIYz30T/hedlBUJCnYLiPft9nfUEUxXye7JJ5H60Ij/+8JA5jG3jGnvE3Y15tKjG9LuT+BOqLOQSw8abjEd9sMPK/FQh06y3+LXrGcqH8EcdOpPPJjT81cjnK4uZvr+V8ovCehia4RCMgtrOPUwPa0IsWzpkF4ovBXdzwXDpRSlquxS5MozgmLugXMJ3eIrANH666Li5TwpEZav2LQQqjC8HJ8ZalNzsoljEG9Y4NNsAMZriziDxtvGgs2AbnQUjxHPCrhqEzO1CmMXk4ePqwLzZfhImmm7TpfiHUs5tQZKQzOnZTUrTNgnbi3mNbFKszCmOw9U8ZwJG0Zo8i0rYYBFgDZH2Bkh95wr7Nyw="
addons:
    code_climate:
        repo_token:
            secure: "Jdse3JIYI47nEnkoMYHq54F8q5MR7OdVYY9XBqoE2jBN57BGDcJP2WkEzmeLnmS8vKgugS/cMKkGbKYVQksv9mNOgVIMv13G/Y0BRAHZv9pFtbINRaVcqLEQ5M+f8oikFNCbyU6crgBU9ekxNCShq35C3BBtDwfnJW4BBEWE3gy76+7JGNDd3BfqBysluuZPBL6rvW16gCb10Insa5R3YEjVidiJ9Wq4A+kZpnmexQVfXoFIQ5HeJMQcITXehg4CwU0TteXSlaBE2zm1dxiBh1yytXOnrHVo2ln8nU93/cwEkCPovpkFcm2Lw96BvyEjbMovdEHY7yEB1oIwt5ZMOzZly7oNgZI8Mhsfa1gJ6TilV5vbbRAdTYOcsNly6fu/f5RZ2EJbWcm7U32EwFKwWHPc0ITaX4N9xPyr+K7B9kvKQrkaZzL5xWlLUTwVpvDqrrTfgzbazT8+Sdbzaf+s70WO2b7L59CyyCAGAwrssc6TfMxlCYDZt4ZRp9xkXYl5xrfSpOg5pQbaZ057YXhAUE+ipA0QLx8ubKZpQ8lLdLghq2C9HXEW08dTg7MwugU7+a6KJCzeiXoeEkYJ6yB0MTzSTP8zkISp5zV5gdmaPAshVAuqqQ3YRZUFi8SBeH3BSJ4cjRNdGKVS3hDgFcG9fdYS4dPlrD3mvRw8kTuutd0="
after_script:
    - npm install codeclimate-test-reporter
    - gulp coverage
    - codeclimate-test-reporter < coverage/lcov.info