language: node_js
node_js:
    - 4.2.2
sudo: false
before_script:
  - npm install gulp
cache:
    directories:
        - node_modules
addons:
    code_climate:
        repo_token:
            secure: "aldWxqRdFf10OWd6N2Q7u8JhYmEbgYMIq9OH/p5JZ5HD5YnzJdeBPiZvhoKUkcGqRBQsY8wDrynYKjbqqLHA4tXjuiLusCEAeh0ycclzVicJKMmyr65jvxTENi8lthK2v20089JhHH20UWMZcE5YyZeRX1rsGpxbMY3pBIql7CdCA5yc3hVTsew30eew6EzGzNhaWpVU13+U75R1TiBcE2zUafEz2+z9Z+4ylVf4C9tqC9Goej0EHgUw4P3iAtuN9hZMyPY9jBBUGMKLPce6M3MJv4IjtMfzF09kVxlU739VlGc+XlrBS7/O8+cdfhzSh7p10Ida/JhhrQwe+YQrx1uuqX/Vw34Yzi9CGVJfICBjeP5BzVKPJoZ/o/1Cjj94lo58Tsec8iNhjRmhZ4e9SWO1Gc34L507sJg4v2gTnREiN7opnFAbFQpbAvLKpFpiSIUP3AwnSTg9sBK0MLQIBfBSh7K1kZyriYZ5+fkXHTDTO+MKKh8dBjI2gVPqopa5nRF+rkIgr6xDs2oVk+Gml3DzqpRJDDU5cajTf+4z+TXENhZuUDWuL/r+TL8om7ga63unGvBDo5i0PYHyVfuIx7csSQy898sd6RK6wizJf36yWxd78MSs3/GHLzdwxQTBNWd3uELmZL2Z5ASxx/zY0F7tuV8ED4xIgAde+Qc1qGc="
after_script:
    - npm install codeclimate-test-reporter
    - gulp coverage
    - codeclimate-test-reporter < coverage/lcov.info