language: node_js
node_js:
    - 4.2.2
sudo: false
before_script:
  - npm install gulp
cache:
    directories:
        - node_modules
addons:
    code_climate:
        repo_token:
            secure: "Jdse3JIYI47nEnkoMYHq54F8q5MR7OdVYY9XBqoE2jBN57BGDcJP2WkEzmeLnmS8vKgugS/cMKkGbKYVQksv9mNOgVIMv13G/Y0BRAHZv9pFtbINRaVcqLEQ5M+f8oikFNCbyU6crgBU9ekxNCShq35C3BBtDwfnJW4BBEWE3gy76+7JGNDd3BfqBysluuZPBL6rvW16gCb10Insa5R3YEjVidiJ9Wq4A+kZpnmexQVfXoFIQ5HeJMQcITXehg4CwU0TteXSlaBE2zm1dxiBh1yytXOnrHVo2ln8nU93/cwEkCPovpkFcm2Lw96BvyEjbMovdEHY7yEB1oIwt5ZMOzZly7oNgZI8Mhsfa1gJ6TilV5vbbRAdTYOcsNly6fu/f5RZ2EJbWcm7U32EwFKwWHPc0ITaX4N9xPyr+K7B9kvKQrkaZzL5xWlLUTwVpvDqrrTfgzbazT8+Sdbzaf+s70WO2b7L59CyyCAGAwrssc6TfMxlCYDZt4ZRp9xkXYl5xrfSpOg5pQbaZ057YXhAUE+ipA0QLx8ubKZpQ8lLdLghq2C9HXEW08dTg7MwugU7+a6KJCzeiXoeEkYJ6yB0MTzSTP8zkISp5zV5gdmaPAshVAuqqQ3YRZUFi8SBeH3BSJ4cjRNdGKVS3hDgFcG9fdYS4dPlrD3mvRw8kTuutd0="
after_script:
    - npm install codeclimate-test-reporter
    - gulp coverage
    - codeclimate-test-reporter < coverage/lcov.info